### ISSUE TITLE
user cannot see their own information alone

### ISSUE THREAD

**Issue by gladys-ghost** [muano-thee-last/Robinhood#8]
now need make it such that you only see the information that is associated with your email. i can't code somethings without this being done first

**Comment by gladys-ghost** [comment]
will do so when the new url is created

**Comment by Goitsee2** [comment]
> now need make it such that you only see the information that is associated with your email. i can't code somethings without this being done first

is this now sorted?????

**Comment by gladys-ghost** [comment]
still doing pc, will be done before the sprint for sure!

**Comment by gladys-ghost** [comment]
this has been solved
